# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
  form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
  input_sync: true
  configs:
    main_config:
      toolbar: full
      extraPlugins: N1ED-editor
      allowedContent: true
      apiKey: 1W0LDFLT
      skin: n1theme
      removePlugins: iframe
      filebrowserBrowseRoute: elfinder
      filebrowserBrowseRouteParameters: []